apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am production!
  labels:
    app: app1
    env: production
  name: production-app1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app1
      deployment: hello
      env: production
  template:
    metadata:
      annotations:
        note: Hello, I am production!
      labels:
        app: app1
        deployment: hello
        env: production
    spec:
      containers:
      - command:
        - /hello
        - --port=8080
        - --enableRiskyFeature=$(ENABLE_RISKY)
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              key: altGreeting
              name: production-app1
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              key: enableRisky
              name: production-app1
        image: monopole/hello:1
        name: the-container
        ports:
        - containerPort: 8080
