apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am staging!
  labels:
    app: app2
    env: staging
  name: staging-app2b
spec:
  ports:
  - port: 8666
    protocol: TCP
    targetPort: 8080
  selector:
    app: app2
    deployment: hello
    env: staging
  type: LoadBalancer
