apiVersion: v1
data:
  altGreeting: Good Morning!
  enableRisky: "false"
kind: ConfigMap
metadata:
  annotations:
    note: Hello, I am staging!
  labels:
    app: app3
    env: staging
  name: staging-app3
