apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
    env: dev
  name: dev-app1
spec:
  ports:
  - port: 8666
    protocol: TCP
    targetPort: 8080
  selector:
    app: app1
    deployment: hello
    env: dev
  type: LoadBalancer
