apiVersion: v1
data:
  altGreeting: Good Morning!
  enableRisky: "false"
kind: ConfigMap
metadata:
  annotations:
    note: Hello, I am production!
  labels:
    app: app1
    env: production
  name: production-app1
