apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am staging!
  labels:
    app: app1
    env: staging
  name: staging-app1
spec:
  ports:
  - port: 8666
    protocol: TCP
    targetPort: 8080
  selector:
    app: app1
    deployment: hello
    env: staging
  type: LoadBalancer
