name: Schedule sync all

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  deploy-all:
    if: github.ref == 'refs/heads/master'
    name: sync
    runs-on: ubuntu-latest
    container: slok/kahoy:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./scripts/ci/deploy.sh sync-all